# A list of available rules and their signatures can be found here: https://buck2.build/docs/api/rules/

cxx_library(
    name = "greet",
    srcs = glob(
        ["src/*.c"],
    )
)

rust_binary(
    name = "main",
    srcs = glob(
        ["src/*.rs"],
    ),
    # How a rust binary depends on a cxx dynamatic library
    # Way 1: depend on a cxx_library task
    deps = [":greet"],
    # Way 2: Directy pass the rustc flags
    # rustc_flags = ["-Lnative=/root/workspace/buck2/rust_build_rs/src", "-ldylib=greet"]
)
